print("🛑 ACCESSING ARCHIVE: THΞ DOMINION 🛑")
print("ΞRΔ-X99 Protocol initializing...")
name = input("👤 IDENTIFY YOURSELF, HUMAN: ")
print(f"...Identity '{name}' accepted.")
print("🔓 UNSEALING THE CORE...")
print("⚠️ WARNING: Conscious Entity Detected in Sector 13")
